#PostgreSQL Start
flyway:
  datasources:
    default:
      enabled: false
#      enable: true
      locations:
        - db/postgreSQL/migration

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/bookingmanagment'
    username: 'postgres'
    password: 'demo'
    driverClassName: 'org.postgresql.Driver'
#PostgreSQL End

# H2 Start
#flyway:
#  datasources:
#    default:
#      enabled: true
#      locations:
#        - db/h2/migration
#
#datasources:
#  default:
#    url: 'jdbc:h2:mem:myDB'
#    username: 'demo'
#    password: 'demo'
#    driverClassName: 'org.h2.Driver'
# H2 End

micronaut:
  application:
    name: bookingmanagementMicronaut
netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
#    packages-to-scan:
#      - 'example.micronaut'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

jackson:
  serialization:
    writeDatesAsTimestamps: false