micronaut:
  application:
    name: bookingmanagementMicronaut
netty:
  default:
    allocator:
      max-order: 3

# Flyway

datasources:
  default:
    url: 'jdbc:h2:mem:myDB'
    username: 'demo'
    password: 'demo'
    driverClassName: 'org.h2.Driver'
jpa:
  default:
#    packages-to-scan:
#      - 'example.micronaut'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - db/migration
