name: Build and Push

on:   
 push:
     branches: [develop]
 workflow_dispatch:

env:
  JAVA_IMAGE_NAME: my-thai-star-java
  ANGULAR_IMAGE_NAME: my-thai-star-angular
  
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Build Java image
        run: docker build . --file java/Dockerfile.githubactions --tag $JAVA_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
        
      - name: Build Angular image
        run: docker build . --file angular/Dockerfile.githubactions --tag $ANGULAR_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
        
      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          JAVA_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$JAVA_IMAGE_NAME
          ANGULAR_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$ANGULAR_IMAGE_NAME
          
          # Change all uppercase to lowercase
          JAVA_IMAGE_ID=$(echo $JAVA_IMAGE_ID | tr '[A-Z]' '[a-z]')
          ANGULAR_IMAGE_ID=$(echo $ANGULAR_IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker push $JAVA_IMAGE_ID
          docker push $ANGULAR_IMAGE_ID
          
