name: Deploy to Okteto

on:
  schedule:
    - cron:  '30 23 * * *'
  workflow_dispatch:

jobs:
  deploy:
    if: ${{github.repository == 'devonfw/my-thai-star'}}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_LOGIN_TOKEN }}
        
    - name: "Activate personal namespace"
      uses: okteto/namespace@latest
      with:
        name:  devonfw-core
    
    - name: "Create deployment"
      uses: okteto/apply@latest
      with:
        manifest: k8s.yml
